
* 2016
** Code
(setq truncate-lines 'nil) (setq truncate-lines 't)

** 2016-02 February
*** 2016-02-16 Tuesday
****This is another test 
Entered on [2016-02-16 Tue 14:55]
  
  [[file:~/org/gtdActionables.org::*This%20is%20a%20test][This is a test]]
*** 2016-02-19 Friday
**** Yesterday work on Scratch files in Cyborganize style 
Entered on [2016-02-19 Fri 07:10]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Learning%20About%20Chi%20(Can%20be%20a%20feeling%20of%20Empowerment%20too!][Learning About Chi (Can be a feeling of Empowerment too!]]
**** Was able to get a response from DA regarding Severance check - see emails
Entered on [2016-02-19 Fri 09:51]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Checked%20Unemployment%20or%20Check%20Unemployment%20Portal][Checked Unemployment or Check Unemployment Portal]]
*** 2016-02-20 Saturday
**** Spent considerable time yesterday following up and depositing serverance check 

Entered on [2016-02-20 Sat 07:40]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Spent%20considerable%20time%20yesterday%20following%20up%20and%20depositing%20serverance%20check][Spent considerable time yesterday following up and depositing serverance check]]
**** Spent quite a bit of time yesterday feeling and expending my energy (3 hrs)

Entered on [2016-02-20 Sat 07:47]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Learning%20About%20Chi%20(Can%20be%20a%20feeling%20of%20Empowerment%20too!][Learning About Chi (Can be a feeling of Empowerment too!]]
**** Yesterday Went out for Cocktails and Dinner Bootleggers and Asian Imperial spent about $120
    - Sometimes at a bar you can do Business networking 
      not sure if anything will become of it, but got contacts card.
 
Entered on [2016-02-20 Sat 08:11]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Went%20out%20for%20Cocktails%20and%20Dinner%20Bootleggers%20and%20Asian%20Imperial%20spent%20about%20$120][Went out for Cocktails and Dinner Bootleggers and Asian Imperial spent about $120]]
**** Spent time today on learning Vim and also best way to start a cmd shell from within Emacs. Does not seem to like to start a cmd shell from an elisp expression. 
Entered on [2016-02-20 Sat 18:55]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Learn%20Vim][Learn Vim]]
**** Developed Opportunities Template for Org-capture
Entered on [2016-02-20 Sat 21:03]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Wake%20Up][Wake Up]]
*** 2016-02-21 Sunday
**** Spent considerable time again yesterday feeling and expending my energy 
Entered on [2016-02-21 Sun 07:32]
  
  [[file:~/org/jtdJournal.org::*2016-02-20%20Saturday][2016-02-20 Saturday]]
**** More development work on org-capture template for opportunities. Refined format of template
and used practically on job listings in Craigslist. Worked up to listings in the 
beginning of Feb. Also worked on some cover letter development.
Entered on [2016-02-21 Sun 20:00]
  
  [[file:~/org/jtdJournal.org::*Spent%20considerable%20time%20again%20yesterday%20feeling%20and%20expending%20my%20energy][Spent considerable time again yesterday feeling and expending my energy]]
*** 2016-02-23 Tuesday
****  Yesterday worked on outputting opportunities.org from ruby.  Also got Office 2003 to work might need to consider wiping and re-installing
Office 2013. Will need to generate populated UI Work Search form from computer. How?  Do not really know yet. 
Entered on [2016-02-23 Tue 06:44]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Jobhunting%20Activities][Visit ETRR Website and Jobhunting Activities]]
**** Worked on Org-Capture and after investigating JSON format have determined that YAML format is ideal for the Opportunities template. Have now 
reconfigured the Or-Capture Opportunities template to output YAML format.
Entered on [2016-02-23 Tue 22:12]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Jobhunting%20Activities][Visit ETRR Website and Jobhunting Activities]]
**** Felt and expended quite a bit of energy today.
Entered on [2016-02-23 Tue 22:23]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Jobhunting%20Activities][Visit ETRR Website and Jobhunting Activities]]
*** 2016-02-24 Wednesday
****  Worked on development of existing Opportunties into proper YAML format. Also started Working on Resume development using automated website
Entered on [2016-02-24 Wed 14:29]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Jobhunting%20Activities][Visit ETRR Website and Jobhunting Activities]]
**** Youtube/internet research on Sexual Sublimation. Will be trying to relate this to NLP anchoring.
Entered on [2016-02-24 Wed 14:38]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Learning%20About%20Chi%20(Can%20be%20a%20feeling%20of%20Empowerment%20too!][Learning About Chi (Can be a feeling of Empowerment too!]]
****  Some Youtube research on NLP anchoring and how it can be used to trigger a high sexual energy state (sexual sublimation)
Entered on [2016-02-24 Wed 14:41]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Look%20at%20NLP%20and%20Psychological%20training][Look at NLP and Psychological training]]
*** 2016-02-25 Thursday
**** Yesterday also worked on Resume Development using Resume Now.
Entered on [2016-02-25 Thu 07:07]
  
  [[file:~/org/jtdJournal.org::*2016-02-24%20Wednesday][2016-02-24 Wednesday]]
**** Worked on Resume using existing Techresume4.doc in Resume-Now Generator.
Entered on [2016-02-25 Thu 08:09]
  
  [[file:c:/Users/Ray/Desktop/scratch19.org::*Customize%20Resume%20from%20Templates][Customize Resume from Templates]]
**** Entered more Resume Templates and Organized Names of Templates. Added
six basic resumes. Still need more updates and customization.
Entered on [2016-02-25 Thu 09:43]
  
  [[file:c:/Users/Ray/Desktop/scratch19.org::*Customize%20Resume%20from%20Templates][Customize Resume from Templates]]
**** Did some more research in anchoring and the swish pattern.
Entered on [2016-02-25 Thu 13:37]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Look%20at%20NLP%20and%20Psychological%20training][Look at NLP and Psychological training]]
*** 2016-02-26 Friday
**** Yesterday Worked quite a bit of time on Resume automation finding a variety
of On-line tools. Some free and open source and others not so much.
Entered on [2016-02-26 Fri 01:36]
  
  [[file:c:/Users/Ray/Desktop/scratch19.org::*Customize%20Resume%20from%20Templates][Customize Resume from Templates]]
**** Significant progress this morning in semi automation of Resume development by using Resume-Now, Screen shotting the results and OCR
the resulting images and then putting (p) them into an org file. This will enable Emacs oriented mix and match of resume creation. By leveraging
the unique powers of each piece of software significant accomplishments might result.
Entered on [2016-02-26 Fri 04:17]
  
  [[file:c:/Users/Ray/Documents/JobSearch/Master%20Templates/OCRTest.org::*Resume%20Copy][Resume Copy]]
**** Researched JSON resume.
Entered on [2016-02-26 Fri 09:30]
  
  [[file:~/org/jtdJournal.org::*Significant%20progress%20this%20morning%20in%20semi%20automation%20of%20Resume%20development%20by%20using%20Resume-Now,%20Screen%20shotting%20the%20results%20and%20OCR][Significant progress this morning in semi automation of Resume development by using Resume-Now, Screen shotting the results and OCR]]
**** Installed Lisp Library w32-Browser.el and using commands w32-Browser and w32Explore
Entered on [2016-02-26 Fri 12:00]
  
  [[file:c:/Users/Ray/Desktop/]]
**** Seriously considering using EMACs as the senior partner for Operating system ... combined with Windows and Browser Firefox. This will have
to be the case moving forward for rapid manufacture of Custom Resumes.
Entered on [2016-02-26 Fri 12:02]
  
  [[file:c:/Users/Ray/Desktop/]]
**** Installed and tested Latex from Org-mode also test earlier outputting to Opendoc
format. This might be the easier way to go. Might need to understand setting styles
more. More updates on the OCRTest.org file template. Was able to output a Latex file
and an Opendoc file, but the default styles are no good for resumes. To customize the Opendoc styling looks to be quite complex, but still 
might be doable. This requires modifying the odt exporter settings.
Entered on [2016-02-26 Fri 20:06]
  
  [[file:~/org/jtdJournal.org::*2016-02-26%20Friday][2016-02-26 Friday]]
**** Major breakthrough! Was able to embed new default styles for ODT exporter by unzipping downloaded template format and moving to org styles
directory and it worked!!
Entered on [2016-02-26 Fri 23:46]
  
  [[file:c:/Users/Ray/Documents/JobSearch/Master%20Templates/OCRTest.org::*Resume%20Copy][Resume Copy]]
*** 2016-02-27 Saturday
**** From very early this morning more work on exporting on the ODT template to capture
formatting. This day had considerable progress considering our all day visit
to Portland Maine.
Entered on [2016-02-27 Sat 07:45]
  
  [[file:c:/Users/Ray/Documents/JobSearch/Master%20Templates/OCRTest.org][file:c:/Users/Ray/Documents/JobSearch/Master Templates/OCRTest.org]]
  
*** 2016-02-28 Sunday
**** From early Saturday morning until early Sunday morning worked on installation 
and use of XML Editor(s) to edit org-odt for resume styling. This might or might not
have caused computer disabling of this computer of many critical functions 
including internet connectivity(computer virus?) Was able to fix by enabling services and
system restore. Also did some work on other computer too and rebooted into Ubuntu need to 
think of a back-up and rescue plan. Performing full system scan right now, since very early this morning. 
Entered on [2016-02-28 Sun 08:39]
  
  [[file:c:/Users/Ray/Documents/JobSearch/Master%20Templates/OCRTest.org::*Resume%20Copy][Resume Copy]]
**** Referencing work done earlier this morning from yesterday. Did additional work on adding Resume and adding 
template cover letter content to to org-odt output.
Entered on [2016-02-28 Sun 08:58]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Jobsearch%20Activities][Jobsearch Activities]]
****  Rebooted into Ubuntu Live USB. Need to set-up other internal/external Hard disk for permanent operating system. Also
later ran anti-virus boot scan. 
Entered on [2016-02-28 Sun 09:06]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Work%20on%20Other%20Computer][Work on Other Computer]]
*** 2016-02-29 Monday
**** Yesterday did some work on setting up template for cover letter. This is set-up in OCRTest.org
Entered on [2016-02-29 Mon 07:18]
  
  [[file:c:/Users/Ray/Documents/JobSearch/MasterTemplates/OCRTest.org::*Basic%20Outline%20Sample%20Coverletter%20Template%20for%20Part-time%20Position][Basic Outline Sample Coverletter Template for Part-time Position]]
**** Considerable work today on developing YAML to CSV and then to formatted spreadsheets from opportunties.org for Job Search documentation.
Essentially covered almost (1) months worth of Jobsearch activities. Also outputted OCRTest.org into org-odt template along with most current 
resume for tomorrow's RESEA meeting at 1:00.

Entered on [2016-02-29 Mon 22:24]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Jobhunting%20Activities][Visit ETRR Website and Jobhunting Activities]]
**** Worked on re-installing Elfa in closet.
Entered on [2016-02-29 Mon 22:49]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Joan%20Time%20Monopoly][Joan Time Monopoly]]
** 2016-03 March
*** 2016-03-01 Tuesday
**** Considerable work up till now prepping for RESEA meeting Getting Resume and Work Search Logs ready. Also considerable about almost 3 hours 
freelance research on ABIWord (getting VI mode to work). Was to be used to edit finished resumes. Also spent time investigating other Word Processor
oriented software wsywyg type stuff like Fonts in Emacs, Pandoc, Nroff, Troff etc....
Entered on [2016-03-01 Tue 11:12]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Jobhunting%20Activities][Visit ETRR Website and Jobhunting Activities]]
**** Went to ETRR for RESEA
Entered on [2016-03-01 Tue 14:25]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Go%20to%20ETRR?][Go to ETRR?]]
**** Set-up closet rod brackets in back room closet.
Entered on [2016-03-01 Tue 21:20]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Joan%20Time%20Monopoly][Joan Time Monopoly]]
**** Adding use of Emacs Client-Server functionality. Also adding "It's all text to Firefox and pointing it to EMACS client. 
At w3schools.com you will learn how to make a website. We offer free tutorials in all web development technologies. 
<= From browser this is another test to see how well this works using "the it's all text system". I'm trying to find the most convenient way to 
return this to the browser. This apparently just stays as a buffer until it is deleted. 
This might have some serious applications when filling out online applications.

Entered on [2016-03-01 Tue 23:22]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*More%20Emacs%20and%20Evil%20Mode%20(Including%20Vim%20Study)][More Emacs and Evil Mode (Including Vim Study)]]
*** 2016-03-02 Wednesday
**** Will be showing 5 Job Search activities for today at least. 
Entered on [2016-03-02 Wed 14:40]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Jobhunting%20Activities][Visit ETRR Website and Jobhunting Activities]]
**** Moved money by going to WCU at Walmart
Entered on [2016-03-02 Wed 21:06]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Check%20Accounts%20and%20Budget][Check Accounts and Budget]]
**** Reviewed numerous Job and Career type Youtube seminars
Entered on [2016-03-02 Wed 21:08]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Jobhunting%20Activities][Visit ETRR Website and Jobhunting Activities]]
*** 2016-03-03 Thursday
**** Organized Practice.org based on GTD principles and good Time Management.
Entered on [2016-03-03 Thu 08:56]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Time%20Management][Time Management]]
**** Yesterday revised bookmarking to link to external hard-drive
Entered on [2016-03-03 Thu 15:12]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*System%20Administration%20and%20Personal%20Desktop%20Support][System Administration and Personal Desktop Support]]
****  Reviewed how to create tags.
Entered on [2016-03-03 Thu 19:37]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Learn%20Org%20Mode][Learn Org Mode]]
**** Payed WCU credit card
Entered on [2016-03-03 Thu 13:41]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Budgeting%20and%20Bills][Budgeting and Bills]]
**** Using Fix a Flat re-inflated tire will need to get car to Brian's for other things like idiot sensor messages.
Entered on [2016-03-03 Thu 13:42]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Fixed%20Tire][Fixed Tire]]
****  Went grocery shopping and bought Baking Powder, Kosher Salt, Chicken Wings, Vodka,Sweet Potato and Asparagus for Tempura

Entered on [2016-03-03 Thu 14:19]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Grocery%20Shopping%20and%20Run%20Errands][Grocery Shopping and Run Errands]]
**** Put up bulbs in bathroom and dusted fixtures 
Entered on [2016-03-03 Thu 14:23]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Joan%20Time%20MonopolyO%20Lightbulbs%20in%20Bathroom%20switch%20them?][Joan Time Monopoly Lightbulbs in Bathroom switch them?]]
**** Sent initial payment $30 indicating that a payment arrangement needs to be set-up with State revenue office.
Entered on [2016-03-03 Thu 14:27]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Address%20Tax%20Issue][Address Tax Issue]]
*** 2016-03-04 Friday
**** Yesterday spent considerable time on TIME MANAGEMENT and how it integrates with GTD and GTD tools. In addition explored other Time Management
ideas. This morning reviewed On-line seminar "Why Smart People Underperform" by Marie Forleone.
Entered on [2016-03-04 Fri 07:31]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Time%20Management][Time Management]]
**** Got started learning Git and Github. You can use Git for many other purposes other than coding.
Entered on [2016-03-04 Fri 15:12]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*%5B%5Bhttp://searchsoftwarequality.techtarget.com/definition/Scrum-sprint%5D%5BGit,%20Sprint,%20Scrum%5D%5D%20and%20Agile%20development][{{http://searchsoftwarequality.techtarget.com/definition/Scrum-sprint}{Git, Sprint, Scrum}} and Agile development]]
*** 2016-03-05 Saturday
**** Yesterday reviewed budget and WCU account.
Entered on [2016-03-05 Sat 06:17]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Budgeting%20and%20Bills][Budgeting and Bills]]
**** Yesterday morning attended more on-line seminars.
Entered on [2016-03-05 Sat 06:19]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Jobhunting%20Activities][Visit ETRR Website and Jobhunting Activities]]
**** Yesterday dropped car off to Brians to fix tire and check computer settings.
Entered on [2016-03-05 Sat 06:25]
  
  [[file:~/org/jtdJournal.org::*2016-03-05%20Saturday][2016-03-05 Saturday]]
**** Starting yesterday upgraded to Eclipse RCP platform. Now in search of optimum tutorial.
Entered on [2016-03-05 Sat 06:50]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Eclipse%20Tutorial][Eclipse Tutorial]]
**** Added Supermemory to morning rituals
Entered on [2016-03-05 Sat 06:59]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*SuperMemory][SuperMemory]]
**** Will try start implementing JTD consciously. Added tool a simple notebook...
Entered on [2016-03-05 Sat 07:29]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*GTM%20Stuff][GTM Stuff]]
**** installed Vimperator into Firefox also note Vim like keybindings are available for Thunderbird.
Entered on [2016-03-05 Sat 08:16]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Learn%20Vimperator][Learn Vimperator]]
**** Adding the Swiss cheese task management system to repertoire which I have been doing all along.
Entered on [2016-03-05 Sat 13:11]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Other%20Time%20Management%20Stuff][Other Time Management Stuff]]
**** In addition to required Job search activity, updated Jobsearch file using yaml to excel file for Job search log. Created new Sales Oriented
resume. Need to do Tech version and Customer Service version.
Entered on [2016-03-05 Sat 20:23]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Jobhunting%20Activities][Visit ETRR Website and Jobhunting Activities]]
*** 2016-03-06 Sunday
**** Found it is possible to customize Org Appearance with fonts.
Entered on [2016-03-06 Sun 01:00]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Customize%20Org%20appearance][Customize Org appearance]]
**** Study and practice with Font-setting in Org-Mode
Entered on [2016-03-06 Sun 01:09]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Org-Mode][Org-Mode]]
**** Picked up car from Brian, but need to follow up and pay him.
Entered on [2016-03-06 Sun 07:27]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Fix%20Tire%20get%20it%20to%20Brian's%20and%20now%20pick%20it%20up%20today.][Fix Tire get it to Brian's and now pick it up today.]]
**** This morning focused on re-organizing master list to simplify using org-mode to fewer upper level items.
Entered on [2016-03-06 Sun 08:11]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Time%20Management][Time Management]]
**** Filed request for this week
Entered on [2016-03-06 Sun 10:06]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Checked%20Unemployment%20or%20Check%20Unemployment%20Portal][Checked Unemployment or Check Unemployment Portal]]
**** Additional refinements on Resume masters org versions and odt versions.
Entered on [2016-03-06 Sun 22:36]
  
  [[file:c:/Users/Ray/Documents/JobSearch/MasterTemplates/OCRTestRecrafted.org::*Resume%20Copy][Resume Copy]]
**** Some more study and initial practice using Git. Git init in Appdata directory?
Entered on [2016-03-06 Sun 23:11]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*%5B%5Bhttp://searchsoftwarequality.techtarget.com/definition/Scrum-sprint%5D%5BGit,%20Sprint,%20Scrum%5D%5D%20and%20Agile%20development][{{http://searchsoftwarequality.techtarget.com/definition/Scrum-sprint}{Git, Sprint, Scrum}} and Agile development]]
*** 2016-03-07 Monday
**** Our own stuff, but had to spend a considerable amount of time AND money to dispose
of Raymond's recycling and trash.
Entered on [2016-03-07 Mon 10:06]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Take%20Out%20Trash%20and/or%20Recycling][Take Out Trash and/or Recycling]]
**** Called Brian no charge!!
Entered on [2016-03-07 Mon 11:17]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Pay%20Brian%20for%20fixing%20tire%20.][Pay Brian for fixing tire .]]
**** Started classic inbox processing.
Entered on [2016-03-07 Mon 15:36]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*GTD%20Stuff][GTD Stuff]]
**** Worked on customizing New Tech resume.
Entered on [2016-03-07 Mon 15:38]
  
  [[file:c:/Users/Ray/Desktop/scratch19.org::*Customize%20Resume%20from%20Templates][Customize Resume from Templates]]
**** Cleaned-up backstairs hall ways for appraisal
Entered on [2016-03-07 Mon 15:40]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Joan%20Time][Joan Time]]
**** Attended more on-line seminars
Entered on [2016-03-07 Mon 21:22]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Jobsearch%20Activities%20%5B%5BJobhunting-activities%5D%5D][Jobsearch Activities {{Jobhunting-activities}}]]
*** 2016-03-08 Tuesday
**** Paid Paypal Credit and paying Bofa over phone, ordered billing checklist by date
Entered on [2016-03-08 Tue 07:40]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Budgeting%20and%20Bills][Budgeting and Bills]]
**** Added hyperlinks and paid Comcast
Entered on [2016-03-08 Tue 09:03]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Budgeting%20and%20Bills][Budgeting and Bills]]
**** Considerable time on learning Git and started populating Github respositories.
Entered on [2016-03-08 Tue 21:28]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*%5B%5Bhttp://searchsoftwarequality.techtarget.com/definition/Scrum-sprint%5D%5BGit,%20Sprint,%20Scrum%5D%5D%20and%20Agile%20development][{{http://searchsoftwarequality.techtarget.com/definition/Scrum-sprint}{Git, Sprint, Scrum}} and Agile development]]
*** 2016-03-09 Wednesday
**** Starting morning doing extended research on journaling alternatives
to include privacy also exploration re: BitBucket and BitBucket like and
related concepts for code and journaling storage.
Entered on [2016-03-09 Wed 07:35]

[[file:c:/Users/Ray/Desktop/practice.org::*%5B%5Bhttp://searchsoftwarequality.techtarget.com/definition/Scrum-sprint%5D%5BGit,%20Sprint,%20Scrum%5D%5D%20and%20Agile%20development][{{http://searchsoftwarequality.techtarget.com/definition/Scrum-sprint}{Git, Sprint, Scrum}} and Agile development]]
**** Significant additional work on developing New Tech Resume.
Entered on [2016-03-09 Wed 10:35]
  
  [[file:c:/Users/Ray/Desktop/scratch19.org::*Customize%20Resume%20from%20Templates][Customize Resume from Templates]]
**** Added concept of browser history as a journal of sorts.
Entered on [2016-03-09 Wed 10:58]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*GTD%20Revisit%20Cyborganized%20Video%20and%20other%20stuff%20(Execution%20Loop)][GTD Revisit Cyborganized Video and other stuff (Execution Loop)]]
*** 2016-03-10 Thursday
**** Yesterday explored additional uses of Git, Bitbucket and the idea and possiblility of uploading from a local wamp server to Wordpress
     Need to remember can publish and unpublish entries for Journaling purposes.
     Entered on [2016-03-10 Thu 08:47]
     
     [[file:c:/Users/Ray/Desktop/practice.org::*%5B%5Bhttp://searchsoftwarequality.techtarget.com/definition/Scrum-sprint%5D%5BGit,%20Sprint,%20Scrum%5D%5D%20and%20Agile%20development][{{http://searchsoftwarequality.techtarget.com/definition/Scrum-sprint}{Git, Sprint, Scrum}} and Agile development]]
****  Some research on Kundalini and Meditation Using the Perineal lock
      Entered on [2016-03-10 Thu 08:51]
      
      [[file:c:/Users/Ray/Desktop/practice.org::*Freelance%20Research][Freelance Research]]
**** Yesterday made pizzas on grill but I believe the key is pre-grilling on pizza stone (maybe both sides) and then finish in Nu Wave after
     adding toppings. Like splitting dough in half.
     Entered on [2016-03-10 Thu 08:53]
     
     [[file:c:/Users/Ray/Desktop/practice.org::*Dinner%20Ideas%20or%20Go%20Out%20or%20Order%20Out%20and%20after%20Dinner][Dinner Ideas or Go Out or Order Out and after Dinner]]
****  From yesterday to today ran Windows update
      Entered on [2016-03-10 Thu 09:11]
      
      [[file:c:/Users/Ray/Desktop/practice.org::*Routine%20System%20Operation%20to%20Optimize%20systems][Routine System Operation to Optimize systems]]
**** This is already in the journal for yesterday 
     Entered on [2016-03-10 Thu 09:56]
     
     [[file:c:/Users/Ray/Desktop/practice.org::*Pizza%20on%20Grill][Pizza on Grill]]
*** 2016-03-11 Friday
**** Yesterday into today adding data into Ditto re: past employment and job application data
     Entered on [2016-03-11 Fri 06:43]
     
     [[file:c:/Users/Ray/Desktop/practice.org::*Jobsearch%20Activities%20%5B%5BJobhunting-activities%5D%5D][Jobsearch Activities {{Jobhunting-activities}}]]
**** Yesterday Mass Jobquest Update
Entered on [2016-03-11 Fri 07:04]
  
  [[file:~/org/opportunities.org::*%20OPPORTUNITY:%20Massachusetts%20Jobquest%20Update][<2016-03-10 Thu 14:23> OPPORTUNITY: Massachusetts Jobquest Update]]
**** Went over some key navigation keys H for back one page and it seems sometimes some of the keys do not work like hinting.
Entered on [2016-03-11 Fri 07:39]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Learn%20Vimperator][Learn Vimperator]]
**** Uploaded OrgDesktopWindows to Github (practice.org). Quite impressive and have some further ideas.
Entered on [2016-03-11 Fri 09:17]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*%5B%5Bhttp://searchsoftwarequality.techtarget.com/definition/Scrum-sprint%5D%5BGit,%20Sprint,%20Scrum%5D%5D%20and%20Agile%20development][{{http://searchsoftwarequality.techtarget.com/definition/Scrum-sprint}{Git, Sprint, Scrum}} and Agile development]]
**** Develop additional Data-entry (populated) data for ditto.
Entered on [2016-03-11 Fri 10:59]
  
  [[file:c:/Users/Ray/Desktop/practice.org::Jobhunting-activities]]
**** Actually sent (2) bona fide job opportunities out using new system. Still need some refinements to process. Can now use Ditto to set-up an
initial coverletter. Finding that I am referring all over the place in the file system to generate resume information. Will need to refine that
Entered on [2016-03-11 Fri 16:57]
  
  [[file:~/org/opportunities.org::*Opportunities:][Opportunities:]]
**** Ran a new commit to practice.org pushed to github
Entered on [2016-03-11 Fri 20:00]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*%5B%5Bhttp://searchsoftwarequality.techtarget.com/definition/Scrum-sprint%5D%5BGit,%20Sprint,%20Scrum%5D%5D%20and%20Agile%20development][{{http://searchsoftwarequality.techtarget.com/definition/Scrum-sprint}{Git, Sprint, Scrum}} and Agile development]]
*** 2016-03-12 Saturday
**** Considerable time this morning re-orging practice.org (some major changes)
Entered on [2016-03-12 Sat 07:34]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*GTD%20Stuff][GTD Stuff]]
**** Added .emacs link to file and link to history text in home directory
Entered on [2016-03-12 Sat 08:25]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*System%20Administration%20and%20Personal%20Desktop%20Support][System Administration and Personal Desktop Support]]
**** Transfered money for Babies birthday tomorrow.
Entered on [2016-03-12 Sat 08:30]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Budgeting%20and%20Bills][Budgeting and Bills]]
**** Committed new changes to practice.org and added command to list for git-bash
Entered on [2016-03-12 Sat 08:49]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*%5B%5Bhttp://searchsoftwarequality.techtarget.com/definition/Scrum-sprint%5D%5BGit,%20Sprint,%20Scrum%5D%5D%20and%20Agile%20development][{{http://searchsoftwarequality.techtarget.com/definition/Scrum-sprint}{Git, Sprint, Scrum}} and Agile development]]
*** 2016-03-13 Sunday
**** Spent considerable time yesterday shopping at Macy's, Walmart and Michael's to put together basket theme. Also touched base with Raymond
about stuff.
Entered on [2016-03-13 Sun 03:01]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Babies%20Birthday][Babies Birthday]]
**** In the wee hours of the morning updated YAML content also added additional
workflow information where appropriate re: Jobsearch activities.
Entered on [2016-03-13 Sun 09:43]
  
  [[file:c:/Users/Ray/Desktop/scratch19.org::*Make%20sure%20Jobsearch%20is%20documented%20properly%20per%20UI][Make sure Jobsearch is documented properly per UI]]
**** Filed UI Benefits for Last Week
Entered on [2016-03-13 Sun 10:23]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Checked%20Unemployment%20or%20Check%20Unemployment%20Portal][Checked Unemployment or Check Unemployment Portal]]
**** Started exploring a number of things including, Github, Gist, Gisto,  BitBucket and Evernote and somehow integrating this all with Emacs. I was
not aware of the anonymous Gist too. The riches of the internet are just incredible. Revisited my Evernote account also.
Entered on [2016-03-13 Sun 21:13]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*%5B%5Bhttp://searchsoftwarequality.techtarget.com/definition/Scrum-sprint%5D%5BGit,%20Sprint,%20Scrum%5D%5D%20and%20Agile%20development][{{http://searchsoftwarequality.techtarget.com/definition/Scrum-sprint}{Git, Sprint, Scrum}} and Agile development]]
*** 2016-03-14 Monday
**** Did classical GTD In-box Sort
Entered on [2016-03-14 Mon 08:25]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Time%20Management][Time Management]]
**** Yesteday as it might have been logged already was exploring further integration of EMACS with Evernote.
Entered on [2016-03-14 Mon 08:33]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Freelance%20Research][Freelance Research]]
**** Reviewed Org-mode tutorial will add as an opportunity activity.
Entered on [2016-03-14 Mon 11:14]
  
  [[file:c:/Users/Ray/Desktop/practice.org::Learn-Org-Mode]]
**** Spent a fair amount of time this morning getting new ear buds in place and reviewing other listening devices on hand
Entered on [2016-03-14 Mon 11:44]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Meditate][Meditate]]
**** This job is no longer available after calling number.
Entered on [2016-03-14 Mon 13:26]
  
  [[file:~/org/opportunities.org::*%5B#A%5D%20OPPORTUNITY:%20Auction%20Drivers%20Needed...Daily%20Pay%20Available.....%20(Worcester%20Area)][<2016-02-28 13:55> OPPORTUNITY:  Auction Drivers Needed...Daily Pay Available..... (Worcester Area)]]
**** Spent some time getting Sidekick account to work on gmail address from DA old address. Also noted confusion with Hubspot account.
Entered on [2016-03-14 Mon 14:19]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Sidekick/Hubspot][Sidekick/Hubspot]]
*** 2016-03-15 Tuesday
**** Starting from yesterday into this morning spent a lot of time on organizing 
and backing up bookmarks (also using auto dedupe tool)
Entered on [2016-03-15 Tue 07:57]
**** Sent letter to Raymond and forwarded to Joan
Entered on [2016-03-15 Tue 11:52]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Breakdown%20cellphone%20bill%20-%20make%20a%20spreadsheet%20and%20need%20to%20write%20letter][Breakdown cellphone bill - make a spreadsheet and need to write letter]]
**** Restarted system (sluggish) Culprit I believe is Chrome as in combo with
Firefox is a load on the system.
Entered on [2016-03-15 Tue 21:09]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Routine%20System%20Operation%20to%20Optimize%20systems][Routine System Operation to Optimize systems]]
**** Will establish the Documents folder as the folder for sending "finished resumes" from.
Entered on [2016-03-15 Tue 21:13]
  
  [[file:c:/Users/Ray/Desktop/scratch19.org::*Customize%20Resume%20from%20Templates][Customize Resume from Templates]]
**** Sent out first Sales oriented cover letter/resume also tailored for part-time
Entered on [2016-03-15 Tue 21:17]
  
  [[file:c:/Users/Ray/Desktop/scratch19.org::*Customize%20Resume%20from%20Templates][Customize Resume from Templates]]
**** Set-up using Sidekick in Chrome to send first Sales Oriented Coverletter/Resume part-time combo cut and paste
Entered on [2016-03-15 Tue 21:25]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Sidekick/Hubspot][Sidekick/Hubspot]]
*** 2016-03-16 Wednesday
**** Resent previous resumes via Sidekick this morning again. For tracking purposes.
Entered on [2016-03-16 Wed 09:21]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Sidekick/Hubspot][Sidekick/Hubspot]]
**** Started some research related to Linkedin spurred by internet marketing thoughts.
Entered on [2016-03-16 Wed 09:25]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Sort%20of%20related%20need%20to%20build%20on-line%20presence%20LinkedIn,%20GitHub%20and%20FaceBook.][Sort of related need to build on-line presence LinkedIn, GitHub and FaceBook.]]
**** Got response from Raymond and forwarded to Joan
Entered on [2016-03-16 Wed 09:50]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Breakdown%20cellphone%20bill%20-%20make%20a%20spreadsheet%20and%20need%20to%20write%20letter][Breakdown cellphone bill - make a spreadsheet and need to write letter]]
**** Ordered networking cards ~ $20.00 (They make money on shipping and internet marketing tactics)
Entered on [2016-03-16 Wed 11:01]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Jobhunting%20Activities%20<<Jobhunting-activities>>][Visit ETRR Website and Jobhunting Activities <<Jobhunting-activities>>]]
**** Created BitBucket Account
Entered on [2016-03-16 Wed 15:13]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*%5B%5Bhttp://searchsoftwarequality.techtarget.com/definition/Scrum-sprint%5D%5BGit,%20Sprint,%20Scrum%5D%5D%20and%20Agile%20development][{{http://searchsoftwarequality.techtarget.com/definition/Scrum-sprint}{Git, Sprint, Scrum}} and Agile development]]
*** 2016-03-17 Thursday
**** Starting from yesterday into this morning reearch into internet marketing (almost all of it is essentially scamming) , but might be
able to derive some insights as I move along.
Entered on [2016-03-17 Thu 03:39]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Internet%20Marketing%20-%20What%20is%20it?][Internet Marketing - What is it?]]
**** Added some inportant notes re: Time Management Stuff after research foray into Internet Marketing like "Stop Learning Internet Marketing,
"Stop Learning... Start Implementing", "The Best Way to be in Business is to be in Business" and "The Law of Five".
Entered on [2016-03-17 Thu 04:14]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Other%20Time%20Management%20Stuff][Other Time Management Stuff]]
**** System reboot and killed process hogs on restart
Entered on [2016-03-17 Thu 10:57]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Routine%20System%20Operation%20to%20Optimize%20systems][Routine System Operation to Optimize systems]]
**** Started more research  on developing LinkedIn profile. Actually started editing profile. This will take a lot of work and thinking. I will 
need to develop this before I started sending resumes and coverletters.
     
Entered on [2016-03-17 Thu 12:46]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Sort%20of%20related%20need%20to%20build%20on-line%20presence%20LinkedIn,%20GitHub%20and%20FaceBook.][Sort of related need to build on-line presence LinkedIn, GitHub and FaceBook.]]
*** 2016-03-18 Friday
**** Some extensive time this morning from 3 AM researching more on LinkedIn and also research on adding partner, reseller and possibly 
affiliate relationships to network marketing scheme. Interesting thing is discovering Salesforce itself is an expensive "partnership"
program (not unlike MLM scams.) I will start along the lines as an Appexchange type partner as it is (I think) free for developers. Need
to develop website first though.
Entered on [2016-03-18 Fri 06:04]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Sort%20of%20related%20need%20to%20build%20on-line%20presence%20LinkedIn,%20GitHub%20and%20FaceBook.][Sort of related need to build on-line presence LinkedIn, GitHub and FaceBook.]]
**** See today's Opportunities will be focusing on productivity viewing Seminars Successful by Design
Entered on [2016-03-18 Fri 11:09]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Other%20Time%20Management%20Stuff][Other Time Management Stuff]]
**** Restarted system and will try to reduce number of tabs being run by Firefox as well as killing processes
Entered on [2016-03-18 Fri 11:11]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Routine%20System%20Operation%20to%20Optimize%20systems][Routine System Operation to Optimize systems]]
**** Sort of unemployment related sent copy of Cobra bill to Jennifer Childress.
Entered on [2016-03-18 Fri 11:35]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Checked%20Unemployment%20or%20Check%20Unemployment%20Portal][Checked Unemployment or Check Unemployment Portal]]
****  Texted message to Raymond about looking at his apartment Monday.
Entered on [2016-03-18 Fri 13:48]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Send%20Message%20to%20Raymond%20http://comcast.net][Send Message to Raymond  http://comcast.net]]
**** Moved boxes and fixed hinge mounts. Also cleaned bathroom
Entered on [2016-03-18 Fri 14:03]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Joan%20Time][Joan Time]]
**** As requested by Joan put Verizon and Macy's on bill.
Entered on [2016-03-18 Fri 14:39]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Budgeting%20and%20Bills][Budgeting and Bills]]
*** 2016-03-19 Saturday
**** Started off morning outlining LinkedIn from web seminar
"How to Create a Killer LinkedIn Profile".
Entered on [2016-03-19 Sat 08:05]
  
  [[file:c:/Users/Ray/Desktop/scratch22.org::*Professional%20Headline][Professional Headline]]
**** Actually a lot of what I did yesterday on LinkedIN IS "Internet Marketing"
Entered on [2016-03-19 Sat 08:11]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Internet%20Marketing%20-%20What%20is%20it?][Internet Marketing - What is it?]]
**** Added link in Practice.org to BitBucket
Entered on [2016-03-19 Sat 08:27]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*%5B%5Bhttp://searchsoftwarequality.techtarget.com/definition/Scrum-sprint%5D%5BGit,%20Sprint,%20Scrum%5D%5D%20and%20Agile%20development][{{http://searchsoftwarequality.techtarget.com/definition/Scrum-sprint}{Git, Sprint, Scrum}} and Agile development]]
**** Yesterday attended on-line seminar and added link to GTD section re: To-Do Lists are evil.
Entered on [2016-03-19 Sat 08:32]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*GTD%20Revisit%20Cyborganized%20Video%20and%20other%20stuff%20(Execution%20Loop)][GTD Revisit Cyborganized Video and other stuff (Execution Loop)]]
**** Rebooted system after keyboard dropped. This seems to have brought system back to normal.
Entered on [2016-03-19 Sat 21:41]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Routine%20System%20Operation%20to%20Optimize%20systems][Routine System Operation to Optimize systems]]
*** 2016-03-20 Sunday
**** Started selecting prospective directories for code respositories
Entered on [2016-03-20 Sun 00:37]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*%5B%5Bhttp://searchsoftwarequality.techtarget.com/definition/Scrum-sprint%5D%5BGit,%20Sprint,%20Scrum%5D%5D%20and%20Agile%20development][{{http://searchsoftwarequality.techtarget.com/definition/Scrum-sprint}{Git, Sprint, Scrum}} and Agile development]]
**** resigned up for Heroku. This enables creating Apps in the cloud and also co-deploys if desired
with Salesforce.
Entered on [2016-03-20 Sun 08:03]
**** Again signed up for Heroku
Entered on [2016-03-20 Sun 08:16]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*%5B%5Bhttp://searchsoftwarequality.techtarget.com/definition/Scrum-sprint%5D%5BGit,%20Sprint,%20Scrum%5D%5D%20and%20Agile%20development][{{http://searchsoftwarequality.techtarget.com/definition/Scrum-sprint}{Git, Sprint, Scrum}} and Agile development]]
**** Created Yaml file for this week and new My Way or the Highway log.
Entered on [2016-03-20 Sun 10:05]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Jobhunting%20Activities%20<<Jobhunting-activities>>][Visit ETRR Website and Jobhunting Activities <<Jobhunting-activities>>]]
**** Re-formatted code files for uploading to Github. Then uploaded new repository to Github.
called SolutionPortfolioSampleCodeSnippets.git Also as a note might be able to creat a repository by peeling back the Insert Tracking system.
A fair amount of inspiration can be gained from the versatility of the MS Access program. MS Access can interface with SQLite.
Entered on [2016-03-20 Sun 12:07]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*%5B%5Bhttp://searchsoftwarequality.techtarget.com/definition/Scrum-sprint%5D%5BGit,%20Sprint,%20Scrum%5D%5D%20and%20Agile%20development][{{http://searchsoftwarequality.techtarget.com/definition/Scrum-sprint}{Git, Sprint, Scrum}} and Agile development]]
**** Clearly having some issues with keyboard, might need to replace. Rebooted computer twice.
Wire connection issue?
Entered on [2016-03-20 Sun 21:16]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*System%20Administration%20and%20Personal%20Desktop%20Support][System Administration and Personal Desktop Support]]
*** 2016-03-21 Monday
**** Reviewed using agenda view in org-mode M-x org-agenda.
Entered on [2016-03-21 Mon 07:43]
  
  [[file:c:/Users/Ray/Desktop/practice.org::Learn-Org-Mode]]
**** Consolidated and recycled majority of boxes
Entered on [2016-03-21 Mon 10:46]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Upstairs%20Consolidate%20Boxes][Upstairs Consolidate Boxes]]
**** Appraiser came and was shown property.
Entered on [2016-03-21 Mon 11:19]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Prepare%20for%20Appraisal][Prepare for Appraisal]]
****  Majority of morning on research related to Internet marketing which is integral with jobhunting AND business development. Trying to 
develop ideas for blogging and website. Need to develop content to relate to LinkIn profile.
Entered on [2016-03-21 Mon 11:29]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Jobhunting%20Activities%20<<Jobhunting-activities>>%20%5B%5BInternet-Marketing%5D%5D][Visit ETRR Website and Jobhunting Activities <<Jobhunting-activities>>  {{Internet-Marketing}}]]
**** Reviewed set-up of Ruby on Rails on Hostgator decided to build an ROR site
rather than a quick start or Wordpress site. Need to work quickly.
Entered on [2016-03-21 Mon 20:50]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Set-up%20rgnterprises%20mail%20in%20Thunderbird%20and%20Admin%20Website][Set-up rgnterprises mail in Thunderbird and Admin Website]]
*** 2016-03-22 Tuesday
**** Going over Ericstips - online-seminar videos. Need to envision what I should do about own website and LinkedIN strategy as this all 
fits together. Actually quite a bit can be lumped into this strategy as was going over Ericstips again. Virtual Assistant. This whole
process was prompted by yesterday's Resume Dev class.
Entered on [2016-03-22 Tue 21:27]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Reviewing%20Internet%20Marketing][Reviewing Internet Marketing]]
**** Went to ETRR on Resume Development.
Entered on [2016-03-22 Tue]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Go%20to%20ETRR?][Go to ETRR?]]
*** 2016-03-23 Wednesday
****  Ordered Networking cards earlier, today checked on status. Should be delivery from Post Office. Actually delivered today
Entered on [2016-03-23 Wed 10:25]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Jobhunting%20Activities%20<<Jobhunting-activities>>%20%5B%5BInternet-Marketing%5D%5D][Visit ETRR Website and Jobhunting Activities <<Jobhunting-activities>>  {{Internet-Marketing}}]]
**** More review on Erics Tips getting to the meat in terms of evaluating niches on the internet.
Entered on [2016-03-23 Wed 21:51]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Reviewing%20Internet%20Marketing][Reviewing Internet Marketing]]
**** More LinkedIn Research and worked on Profile editing.
Entered on [2016-03-23 Wed 21:55]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Sort%20of%20related%20need%20to%20build%20on-line%20presence%20LinkedIn,%20GitHub%20and%20FaceBook.][Sort of related need to build on-line presence LinkedIn, GitHub and FaceBook.]]
*** 2016-03-24 Thursday
**** Some readings and videos on Hadoop.
Entered on [2016-03-24 Thu 19:41]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Freelance%20Research][Freelance Research]]
**** Uploaded more files into Github respository.
Entered on [2016-03-24 Thu 20:03]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*%5B%5Bhttp://searchsoftwarequality.techtarget.com/definition/Scrum-sprint%5D%5BGit,%20Sprint,%20Scrum%5D%5D%20and%20Agile%20development][{{http://searchsoftwarequality.techtarget.com/definition/Scrum-sprint}{Git, Sprint, Scrum}} and Agile development]]
**** Reviewed multiple tutorials 
Entered on [2016-03-24 Thu 20:47]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Jruby%20Tutorial][Jruby Tutorial]]
*** 2016-03-25 Friday
**** Started this morning early doing a lot of free lance research on Hadoop etc.. and then updating on practice.org and github updates. This
has prompted upgrading priority in studying Jruby and earlier had also researched jruby resources.
Entered on [2016-03-25 Fri 09:43]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Start%20Working%20at%20home][Start Working at home]]
**** Investigated the Cloudera website and links to partnerships and developers
Entered on [2016-03-25 Fri 10:10]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Hadoop][Hadoop]]
**** More on Java, Jruby studies looked at Java classes and saved tutorial code on Github
Entered on [2016-03-25 Fri 14:44]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Jruby%20Tutorial][Jruby Tutorial]]
*** 2016-03-26 Saturday
**** Yesterday into today researched Ayacht and Ayacht's principal.
Entered on [2016-03-26 Sat 04:06]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Opportunity%20Activities%20<<Opportunity-activities>>%20%5B%5BInternet-Marketing%5D%5D][Visit ETRR Website and Opportunity Activities <<Opportunity-activities>>  {{Internet-Marketing}}]]
**** Yesterday into today more research on LinkedIn especially on dual careers
Entered on [2016-03-26 Sat 04:12]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Sort%20of%20related%20need%20to%20build%20on-line%20presence%20LinkedIn,%20GitHub%20and%20FaceBook.][Sort of related need to build on-line presence LinkedIn, GitHub and FaceBook.]]
**** Worked on Linked profile added description, refined dates.
Entered on [2016-03-26 Sat 15:03]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Sort%20of%20related%20need%20to%20build%20on-line%20presence%20LinkedIn,%20GitHub%20and%20FaceBook.][Sort of related need to build on-line presence LinkedIn, GitHub and FaceBook.]]
**** Some research on Marketing Automation on Hubspot. (High First Page Ranking)
Entered on [2016-03-26 Sat 15:44]
  
  [[file:c:/Users/Ray/Desktop/practice.org::Internet-Marketing]]
**** Some practice study on using Vimperator also sort of related "It's All Text" working on LinkedIn profile.
Entered on [2016-03-26 Sat 15:47]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Learn%20Vimperator][Learn Vimperator]]
***** 2016-03-27 Sunday
****** Real problem with keyboard need to periodically reboot for keyboard 
to work.
Entered on [2016-03-27 Sun 21:00]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Keyboard%20Issue][Keyboard Issue]]
****** Updated Worksearch log using YAML and YAML converter.  Filed for UI
Entered on [2016-03-27 Sun 21:12]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Opportunity%20Activities%20<<Opportunity-activities>>%20%5B%5BInternet-Marketing%5D%5D][Visit ETRR Website and Opportunity Activities <<Opportunity-activities>>  {{Internet-Marketing}}]]
****** Most or almost all of today spent on Easter activities including Dinner prep.
Entered on [2016-03-27 Sun 21:14]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Easter][Easter]]
****** Some Vimperator research and practive. Definitely related to Workflow automation.
Entered on [2016-03-27 Sun 21:17]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Learn%20Vimperator][Learn Vimperator]]
****** Starting with Ericstips reasearch related to Internet Marketing, SEO and LinkedIn.
Entered on [2016-03-27 Sun 22:38]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Internet%20Marketing%20-%20What%20is%20it?%20<<Internet-Marketing>>][Internet Marketing - What is it? <<Internet-Marketing>>]]
*** 2016-03-28 Monday
**** Idea is to build on-line presence by creating web pages within github etc.. and then linking to linkedin. And or build presence 
"elsewere" pages etc and linking back to linkedin. 
Entered on [2016-03-28 Mon 07:04]
  
  [[file:c:/Users/Ray/Documents/MasterDailyPlannerAndJournal03-27-16.org::*Sort%20of%20related%20need%20to%20build%20on-line%20presence%20LinkedIn,%20GitHub%20and%20FaceBook.][Sort of related need to build on-line presence LinkedIn, GitHub and FaceBook.]]
**** In excess of 4 hours of research on internet marketing including LinkedIn, Ericstips, Article Marketing and how this might relate to SEO
building and how to develop partnerships in the reseller space. Apparently (at least this is my impression) can obtain free articles from
article directories. I myself am looking to generate content.  I will need to leverage the work of others especially if I can do this at
minimal cost. This will require more research. Still not sure how anyone gets paid in article marketing??
Entered on [2016-03-28 Mon 12:49]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Opportunity%20Activities%20<<Opportunity-activities>>%20%5B%5BInternet-Marketing%5D%5D][Visit ETRR Website and Opportunity Activities <<Opportunity-activities>>  {{Internet-Marketing}}]]
**** Additional research on SEO, linked building and Internet marketing after dinner. Looking at various ways of developing an internet 
presence. This will really require a lot of work. Apparently after additional research people get paid in article marketing by the affiliate
link itself as the create content in various places for free. Free websites, other peoples blogs etc. I think I have seen it even in sports
blogs (where it has nothing to do the with the sports blog!?)
Entered on [2016-03-28 Mon 19:18]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Sort%20of%20related%20need%20to%20build%20on-line%20presence%20LinkedIn,%20GitHub%20and%20FaceBook.][Sort of related need to build on-line presence LinkedIn, GitHub and FaceBook.]]
*** 2016-03-29 Tuesday
**** Began prep this morning for Ayacht interview spent 1 1/2 hours initially. This will be on-going until the actual interview. This
has brought up the possible use of Video and like for my website(s) and product development. I think I will favor screen casts though.
Entered on [2016-03-29 Tue 08:33]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Opportunity%20Activities%20<<Opportunity-activities>>%20%5B%5BInternet-Marketing%5D%5D][Visit ETRR Website and Opportunity Activities <<Opportunity-activities>>  {{Internet-Marketing}}]]
**** High level overview of studies of Erictips to get overall outline of lessons and pinpoint information when needed. Also downloaded 
postentially a considerable amount of content that can be used on free and paid websites.
Entered on [2016-03-29 Tue 13:26]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Internet%20Marketing%20-%20What%20is%20it?%20<<Internet-Marketing>>][Internet Marketing - What is it? <<Internet-Marketing>>]]
*** 2016-03-30 Wednesday
**** Yesterday into midnight this morning started trying to understand Rails tutorial. (Study)
Entered on [2016-03-30 Wed 00:21]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Ruby%20on%20Rails%20Tutorial%20%5B0/1%5D][Ruby on Rails Tutorial {0/1}]]
**** 3 hour study and outlining session of ROR and creating hello_app into github.
Entered on [2016-03-30 Wed 03:21]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*ROR%20Ruby%20on%20Rails][ROR Ruby on Rails]]
**** Noticing some parallels between github markdown and Emacs syntax.
Entered on [2016-03-30 Wed 03:25]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*%5B%5Bhttp://searchsoftwarequality.techtarget.com/definition/Scrum-sprint%5D%5BGit,%20Sprint,%20Scrum%5D%5D%20and%20Agile%20development][{{http://searchsoftwarequality.techtarget.com/definition/Scrum-sprint}{Git, Sprint, Scrum}} and Agile development]]
**** Checked audio on computer for potential interview today seems to be okay.
Entered on [2016-03-30 Wed 08:35]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*System%20Administration%20and%20Personal%20Desktop%20Support][System Administration and Personal Desktop Support]]
**** Worked on prepping for todays interview by more research.
Entered on [2016-03-30 Wed 08:57]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Opportunity%20Activities%20<<Opportunity-activities>>%20%5B%5BInternet-Marketing%5D%5D][Visit ETRR Website and Opportunity Activities <<Opportunity-activities>>  {{Internet-Marketing}}]]
**** Purchased new keyboard
Entered on [2016-03-30 Wed 23:31]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Keyboard%20Issue][Keyboard Issue]]
**** Chkdsk file system repair, cannot do restore, might need to do sys recovery. Deleted massive amount of data prior to back-up.
Entered on [2016-03-30 Wed 23:32]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Work%20on%20Other%20Computer][Work on Other Computer]]
*** 2016-03-31 Thursday
**** Going thru process of backing up important components of other laptop
am considering replacing with Linux Ubuntu Operating system after attempting
a system recovery. System restore and chkdsk file system repair does not work.
Now running SFC /Scannow elevated.
Entered on [2016-03-31 Thu 09:01]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Work%20on%20Other%20Computer][Work on Other Computer]]
**** Re-installed Windows 7 via system recovery. Next is prepping for Ubuntu partition.
Entered on [2016-03-31 Thu 14:17]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Work%20on%20Other%20Computer][Work on Other Computer]]
**** Was able to download install program for MS Access program and maintained record of license key.
Entered on [2016-03-31 Thu 20:30]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*System%20Administration%20and%20Personal%20Desktop%20Support][System Administration and Personal Desktop Support]]
**** Collected interview pre-resources see career bookmark.
Entered on [2016-03-31 Thu 20:44]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Visit%20ETRR%20Website%20and%20Opportunity%20Activities%20<<Opportunity-activities>>%20%5B%5BInternet-Marketing%5D%5D][Visit ETRR Website and Opportunity Activities <<Opportunity-activities>>  {{Internet-Marketing}}]]
** 2016-04 April
*** 2016-04-01 Friday
**** Sent email to Raymond this morning re: bills and also follow-up with Denise re: his courtdate. Follow-up with Joan too. Fair amount of time
was dedicated to these tasks.
Entered on [2016-04-01 Fri 11:46]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Send%20Message%20to%20Raymond%20http://comcast.net][Send Message to Raymond  http://comcast.net]]
**** Additional time spent on some advance interview prepping and working on cover letter for SQL Server Job at Monster.
Entered on [2016-04-01 Fri 11:53]
  
  [[file:~/org/opportunities.org::*%20OPPORTUNITY:%20SQL%20Server%20Database%20Administrator][<2016-03-28 Mon 08:17> OPPORTUNITY: SQL Server Database Administrator]]
**** System preparation and defrag in preparation for installing dual boot to Linux.
Entered on [2016-04-01 Fri 12:08]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Work%20on%20Other%20Computer][Work on Other Computer]]
**** Removed SQL Server 2005 in prep to start studying SQL Server databases if required. 
Entered on [2016-04-01 Fri 12:10]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*System%20Administration%20and%20Personal%20Desktop%20Support][System Administration and Personal Desktop Support]]
**** Shrinking volume on  C drive for Linux. Ended up with 180 GB for Windows and 98 GB for Linux
Entered on [2016-04-01 Fri 14:41]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Work%20on%20Other%20Computer][Work on Other Computer]]
**** Installing Ubuntu grub loader is quite the procedure as it is related to UEFI booting process on > 2010 Windows machines.
reference https://help.ubuntu.com/community/UEFI
Entered on [2016-04-01 Fri 22:51]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Work%20on%20Other%20Computer][Work on Other Computer]]
*** 2016-04-02 Saturday
**** Started reviewing applications stored on raynieva2 computer and removed several exploring the possibility of dual boot also on this computer
Entered on [2016-04-02 Sat 07:45]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Routine%20System%20Operation%20to%20Optimize%20systems][Routine System Operation to Optimize systems]]
**** Reviewed budgeting for this timeframe will revisit tonite again.
Entered on [2016-04-02 Sat 08:03]
  
  [[file:c:/Users/Ray/Desktop/BudgetAndBills.org::*Budgeting%20and%20Bills][Budgeting and Bills]]
**** Note early morning journaling and resetting practice.org is a definite form of time mgmt. As most of my TODOs are project oriented in nature
Entered on [2016-04-02 Sat 08:07]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*Time%20Management][Time Management]]
**** Another entry on time mgmt. My workflow process is somewhat different from the Cyborganize process (execution loop) and even GTD as I do not necessararily
from the bottom up, but continously review goals and projects and work from there.
Entered on [2016-04-02 Sat 08:20]
  
  [[file:c:/Users/Ray/Desktop/practice.org::*GTD%20Revisit%20Cyborganized%20Video%20and%20other%20stuff%20(Execution%20Loop)][GTD Revisit Cyborganized Video and other stuff (Execution Loop)]]
